### ISSUE TITLE
Feedback 2de jaars

### ISSUE THREAD

**Issue by Tolga1999** [christoph3r3w/fix-the-flow-interactive-website#3]
- Zet meer focus op de formulier button, je zou een felle blauwe kleur kunnen gebruiken daarvoor, ik zou ook de positie veranderen van onder naar boven.
- redesign de filter functie, het is moeilijk te begrijpen. 

Formulier zelf is duidelijk en heeft een goeie flow.

**Comment by christoph3r3w** [comment]
i agree, i have done the following for the button 

```CSS

   >button{
        /* appearance: none; */
        flex-grow: 1;
        display: flex;
        font-size: 3rem;
        border: 1.5px solid rgba(255, 255, 255, 0.89);
        padding: var(--vg-s);
        min-width: 2em;
        max-width: 80%;
        border-radius: var(--g-c) ;
        background-color: var(--blue2);
        color: var(--beige);
    
    &:hover{
            translate: 0px -5px;
            filter: drop-shadow(2px 5px 1.5px var(--blue2));
            background: white;
        }
    
    &:active{
            translate: 0px -2px;  
        }
```

And I'm still working on ways to make the filter section more accessible
